### ISSUE TITLE
Additional query parameters

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [Bessamu/ajax-multiselect-nova-field#2]
Hello,

Is it possible to add additional query parameters to filter the results? 
In my case users should only be allowed to select items created by themselves.
I tried adding something like 

` ->optionsModel(Product::where('user_id', 1))` 

but this did not seem to have the desired result.

The rest of the plugin looks great!

**Comment by Bessamu** [comment]
Hi!

It's impossible for now. I will add rules for searching. I do not know when I will do this, but I will try to implement it as soon as possible.

Sorry for the long answers, a lot of work :D

**Comment by Bessamu** [comment]
@brandonkhj thanks for helping
